name: Update README

on:
  schedule:
    - cron: '*/30 * * * *' # Actualización cada 30 minutos
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v3
      - uses: Readme-Workflows/recent-activity@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
